# Generated by Django 5.2.9 on 2026-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_address_order_full_name_order_payment_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
